version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: blockchain-investment-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    restart: unless-stopped

  # Backend service
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: blockchain-investment-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://root:rootpassword@mongodb:27017/blockchain-investment?authSource=admin
      - SESSION_SECRET=your_session_secret_here
      - PORT=5000
    depends_on:
      - mongodb
    networks:
      - app-network
    restart: unless-stopped

  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: blockchain-investment-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local